### ISSUE TITLE
Dashboard won't show in mobile devices

### ISSUE THREAD

**Issue by kimpla7** [Autodesk-Forge/bim360appstore-viewer-nodejs-visual.reports#33]
Hi all,

As the title says, I'm not able to visualize the dashboard on mobile devices. I have tried both iOS and Android and it just doesn't appear. Any ideas on how to adapt the code and solve this?

Thank you.

**Comment by augustogoncalves** [comment]
@kimpla7 it does work on mobile, but the UI is not optimized, so hard to navigate. This sample was not designed as a mobile dashboard, sorry.
