### ISSUE TITLE
Support EU endpoint for Viewer

### ISSUE THREAD

**Issue by augustogoncalves** [Autodesk-Forge/bim360appstore-viewer-nodejs-visual.reports#34]
@jaimerosales please check if this https://forge.autodesk.com/blog/bim-360-docs-api-changes-access-data-european-data-center works for this sample, I suspect not based on https://github.com/Autodesk-Forge/bim360appstore-viewer-nodejs-visual.reports/blob/master/www/js/forge.viewer.js#L51

**Comment by jaimerosales** [comment]
I don't think it does, I will probably will have to add the 

api: 'derivativeV2' + (atob(urn.replace('_', '/')).indexOf('emea') > -1 ? '_EU' : '')
to the options object.
